services:

  postgres:
    image: postgis/postgis:16-3.4

    container_name: pgis-postgis-v2

    environment:
      POSTGRES_DB: spatialdb
      POSTGRES_USER: spatialuser
      POSTGRES_PASSWORD: spatialpassword

    ports:
      - "5433:5432"

  backend:
    build: ./backend

    container_name: pgis-api-v2

    ports:
      - "8000:8000"

    depends_on:
      - postgres
